# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: faafe15b1adc6c338007645b78b704c5beb52c44e71bbe7e0f355dc13202df09f68733737fb00630a6d573911aa9b379e102995104503c1239769f4ae0fc4596

test:
  secret_key_base: a0e1948431105e6599137e28143468110c43a94709206ac9a0f87eadde09c4032b2baa8a417046697617f2ca26a3d5349ff667799f205ed6de36daeb6e178496

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
